# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Script Task
    init: echo 'init script' # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    env: 
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      echo 'start script'
      cd /workspace/aws_install
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
      rm -rf awscliv2.zip
      rm -rf /workspace/aws-solutions-architect/aws

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports

# ports:
#   - name: Frontend
#     description: Port 3000 for the frontend
#     port: 3000
#     onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart